#!/usr/bin/env ruby

#
# Utility that answers the questions:
#   How many seconds in 1 month?
#   How many minutes in 39458494 seconds?
#   How many seconds till 10:00pm?
#   How many months till 2034-12-2?
#   ...and many more
#

require "optparse"

module HowMuch
    class OptionsParser
        class Options
            attr_accessor :type

            def initialize
                self.type = :float
            end
        end

        def self.parse(args)
            @options = Options.new
            @parser ||= OptionParser.new do |parser|
                parser.banner = <<USAGE
Usage:

./how-many <units> in NUMBER <units> [options]
./how-many <units> till <time|date|datetime> [options]

units       is one of the following: seconds, minutes, days, weeks,
            months, or years. The first unit specified is usually the smaller.

in          unit conversion from the first units specified to the second. For
            example, specifying ./howmany seconds in 24 hours will tell you
            how many seconds are in 24 hours.

**Below Options Not Implemented Yet**
till        calculate how many units till time/datetime. For example,
            specifying ./howmany days till 2020/08/10 will tell you how many
            days it is until the 8th of October 2020.

time        is a time specified as hh:mm:ss (am|pm) in 12h or 24h

date        is a date, specified in whatever your local date format is.
            Remember to escape special shell chars (if any) and spaces, or
            just surround your date with quotes.

datetime    is a datetime, with date formatted as described as above,
            and time formatted as described above also.
USAGE
                parser.separator ""
                parser.separator "Options"

                parser.on("-tTYPE", "--type=TYPE", [:f, :float, :i, :integer, :int],
                          "output type, f for float (default), i for integer (result will be rounded up)") do |type|
                    p.type
                    @options.type = type
                end

                parser.on_tail("-h", "--help", "show this message") do
                    puts parser
                    exit
                end
                parser.on_tail("-V", "--version", "show program version") do
                    puts App.version
                    exit
                end
            end.parse!

            @options
        end
    end

    class App
        @@version = "0.0.1"
        
        def self.version
            @@version
        end

        def parse_positional_parameters(args)
            units_pattern =/(second|minute|hour|day|week|fortnight|month|year)/

            @to_units = args.shift
            raise "to units invalid" unless @to_units.match units_pattern

            @operation = args.shift
            raise "operation invalid" unless @operation.match /(in|till)/

            @from_number = args.shift.to_f
            raise "number invalid" unless @from_number > 0.0

            @from_units = args.shift
            raise "from units invalid" unless @from_units.match units_pattern
            
            #strip the 's' from the end of the unit word
            unless @to_units.match /.*s$/
                @to_units = @to_units.slice 0, @to_units.length - 1
            end

            # remove the trailing s on plural time period names
            if @from_units.match /.*s$/
                @from_units = @from_units.slice 0, @from_units.length - 1
            end

            if @to_units.match /.*s$/
                @to_units = @to_units.slice 0, @to_units.length - 1
            end
        end

        def do_calculations
            raise "till operation not yet implemented" if @operation == "till"

            seconds_in = {
                "second" => 1,
                "minute" => 60,
                "hour" => (60*60),
                "day" => (3600*24),
                "week" => (3600*24*7),
                "fortnight" => (3600*24*7*2),
                "month" => (3600*24*7*(52.1429/12)),
                "year" => (3600*24*7*52.1429)
            }

            # calculate the result in seconds
            result_seconds = @from_number * (seconds_in[@from_units])

            # unless the units wanted are not secons, display the result,
            # otherwise calculate the result in whatever units are wanted
            unless @to_units != "seconds"
                STDOUT.puts result_seconds
            else
                result = result_seconds / (seconds_in[@to_units])
                STDOUT.puts result
            end
        end

        def run(args)
            OptionsParser.parse(args)
            unless args.length < 4
                parse_positional_parameters(args)
                do_calculations
            else
                display_usage
            end
        end
    end

end

app = HowMuch::App.new
app.run(ARGV)
