#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative('lib/app')
require_relative('lib/options_parser')

#
# Utility that answers the questions:
#   How many seconds in 1 month?
#   How many minutes in 39458494 seconds?
#   How many seconds till 10:00pm?
#   How many months till 2034-12-2?
#   ...and many more
#
#   Created by Jacob Degeling (C) 2017
#   Distributed under the MIT license
#

app = HowMany::App.new
app.run(ARGV)
